### PR TITLE
Use connection_config to detect db

### PR DESCRIPTION
**Pull request by kbrock**
Goal is to inject behavior at include time instead of scope runtime

/cc @ledermann ideas if this will still work for you and/or how I would test that it doesn't break this?
/cc @Fryguy

### CODE REVIEW

**Comment by ledermann** [comment]
This change has issues, too. Using `connection_config` connects to the database, which makes it impossible to use `ancestry` from within a gem. 

My app uses my gem [keepr](https://github.com/ledermann/keepr/) which in turn uses `ancestry`. With this PR, this is the result on starting the rails console:

```
$ rails c
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'keepr'. (Bundler::GemRequireError)
Gem Load Error is: ActiveRecord::ConnectionNotEstablished
Backtrace for gem load error is:
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:124:in `connection_pool'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:120:in `connection_config'
/Users/ledermann/Projects/ancestry/lib/ancestry/has_ancestry.rb:47:in `has_ancestry'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/keepr-0.3.1/lib/keepr/group.rb:4:in `<class:Group>'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/keepr-0.3.1/lib/keepr/group.rb:1:in `<top (required)>'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/keepr-0.3.1/lib/keepr.rb:5:in `<top (required)>'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/Users/ledermann/Projects/myapp/config/application.rb:7:in `<top (required)>'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:77:in `console'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
	from /Users/ledermann/Projects/myapp/config/application.rb:7:in `<top (required)>'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:77:in `console'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/ledermann/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by kbrock** [comment]
@ledermann thanks so much

**Comment by Fryguy** [comment]
@kbrock @ledermann  Is it possible for us to write a test to detect accessing a database early?  That way PRs like this can just fail outright and we would know why, and it would prevent us from adding in the early access again by accident.  I can't think of how to do it.

**Comment by kbrock** [comment]
@Fryguy May be able to ensure that `load_schema` is not called.

**Comment by kbrock** [comment]
test is written - throwing this one away. will try another PR when I get more ideas

**Pull request closed without merging**
