### PR TITLE
Allow arrange serializable to accept block

### PR DESCRIPTION
**Pull request by mastfish**
Should make it nice and easy for anyone to use custom serialisation logic.

### CODE REVIEW

**Comment by stefankroes** [comment]
Excellent! Looks great. One tiny pet peeve: Could you rename childs to children in tests and especially docs? If you are not willing to I'll merge as is but it should be a small effort.

**Comment by mastfish** [comment]
Sure thing - done.

**Comment by stefankroes** [comment]
Merged. Thank you for contributing!

**Comment by defbyte** [comment]
hello there!

I noticed this commit hasn't made its way in to the published Gem. It is present on `2-1-stable` but not the tagged `2.1.0` release. Just wondering when this change will make its way in to the published Gem.

thanks!

**Pull request merged**
