### PR TITLE
Improve documentation around ancestry field and collation

### PR DESCRIPTION
**Pull request by kbrock**
postgres: binary data type is not currently working
mysql: binary data type or string with binary collation is working

Had wanted to go with binary for all, but test would not pass

this updates the comments introduced in #601

### CODE REVIEW

**Comment by kbrock** [comment]
@kshnurov I updated the gem to use `binary` for postgres. The test suite puked.

Staying with the original comments, but put in more documentation to hopefully get this running correctly.

**Comment by kshnurov** [comment]
> @kshnurov I updated the gem to use binary for postgres. The test suite puked.

Ok, after some digging it turns out `pg` gem doesn't unescape `bytea` by default and postgres returns it in hex format.
Here's a solution for postgres, it'll should also solve [this](https://github.com/stefankroes/ancestry/issues/603#issuecomment-1448800893)
```
ALTER DATABASE dbname SET bytea_output to 'escape';
```

With this one, tests are green unless we use `update_strategy = :sql`.
`regexp_replace` isn't possible with binary columns. I'd suggest removing `:sql` update strategy completely.

**Comment by kbrock** [comment]
@kshnurov For a binary ancestry column, what else do I need to specify to set a length? And what value should I use?

```
 Mysql2::Error: BLOB/TEXT column 'ancestry' used in key specification without a key length (ActiveRecord::StatementInvalid)
```

**Comment by kshnurov** [comment]
> For a binary ancestry column, what else do I need to specify to set a length? And what value should I use?

IDK if you missed [this comment](https://github.com/stefankroes/ancestry/pull/601#issuecomment-1437888440)
It definitely shouldn't be a BLOB.

**Comment by kbrock** [comment]
update:
- provided simplified column information and a section with probably way too much detail. After time, this can probably be simplified.
- Added details about using/preferring materialized_path2
- Added configuration file step to default to materialized_path2

**Pull request merged**
