### PR TITLE
[ISSUE-481] uses the new version of primary_key_is_an_integer? only on 4.2+

### PR DESCRIPTION
**Pull request by myxoh**
Note, I don't really know how to proceed for testing here as this is only fixing issue outside of the versions in the `travis.yml` 

I have tested this on a local project

Fixes https://github.com/stefankroes/ancestry/pull/439

### CODE REVIEW

**Comment by kbrock** [comment]
@myxoh Do you want this on master and ancestry 3.x?

**Comment by kbrock** [comment]
The only reason I stopped supporting 4.1 is because installing `mysql` gives me trouble.

I'm more than happy applying any patches you need

**Comment by myxoh** [comment]
Hi. Thanks for merging @kbrock ! If we could have it on master and `ancestry 3.x` that would be great

**Comment by kbrock** [comment]
@myxoh 3.0.6 has been released. let me know if you have any other problems

**Comment by kbrock** [comment]
Fixes #438

**Comment by kbrock** [comment]
@myxoh I'm dropping rails 4.2 soon

are you still using rails 4.x and ancestry master?

**Pull request merged**
