### PR TITLE
I18n support for exception and error strings

### PR DESCRIPTION
**Pull request by kbrock**
fixes #99 from @anthonybatchelor-examtime

Does this still look good?

### CODE REVIEW

**Comment by stefankroes** [comment]
IMHO this isn't useful for the majority of the errors that where localized as they are means to be developer facing, not user facing. Where errors are user facing, I agree that this is useful

**Comment by kbrock** [comment]
Revisiting this.

Most of these errors look like they are developer centric.
Not sure which of these (if any) need to be displayed to the end user.

It did get a number of +1 requests though.

I'll rebase and see how this fairs

**Comment by brunowego** [comment]
@stefankroes please merge this! Thanks @kbrock 👍

**Comment by kbrock** [comment]
kicking

**Comment by kbrock** [comment]
Would having an error code in the exceptions be better than displaying the error to the user.

Seems most of these errors are due to developer error rather than user error.
So using localization seems odd

**Comment by cesarjr** [comment]
Is there any change this pull request to be merged?

**Comment by kbrock** [comment]
@cesarjr I just rebased this PR and it is ready for merge

All of these messages seem to be developer focused.
And typically the purpose of I18N is for updating messages to the end user in the web interface.

A lot of people are asking for this, so I understand that it is desired.
But what do you hope to get with localized error messages since most will not be displayed to the end user?
I'd like to know so I can make sure it meets people's needs.

**Comment by cesarjr** [comment]
Hi!

I'm gonna give you my example.

My model is set to `has_ancestry orphan_strategy: :restrict`.

When the user try to destroy a node with children, ancestry is gonna raise the `Ancestry::AncestryException`.

At the controller I have to rescue this error, check if the message has `/it has descendants/` and send a new message in my language (Portuguese) to the user.

if the message could be translated I just could get the error message and deliver to the user directly.

This is why I think this PR useful in my case.

What do you think about that?

**Review by d-m-u — APPROVED** [review]
i think this looks great, and i think we should have it.

**Pull request merged**
