### PR TITLE
add rails 7 support

### PR DESCRIPTION
**Pull request by chenillen**

### CODE REVIEW

**Comment by kbrock** [comment]
thank you.
I'm hoping to get rails 6.1 support before getting rails 7.0

We mostly have 6.0 but I'm pretty sure the `children.create!` is not working

**Comment by petergoldstein** [comment]
@kbrock Is additional work still required to get Rails 6.1 working (it appears to be passing in CI).  Would you be open to a Rails 7 (and Ruby 3.1) PR at this point?

**Comment by kbrock** [comment]
sorry, that this has not been merged yet.

I merged #577 which is similar/the same

**Comment by kbrock** [comment]
There were strange warnings around 6.1. Specifically `children.create`, since the way rails works for `create` on top of a scope has changed a bit.

Please keep an eye on that in your project, but it looks like it is working.

**Pull request closed without merging**
