### PR TITLE
Adds support for primary_key_format as lined out in the README

### PR DESCRIPTION
**Pull request by walski**
Should fix https://github.com/stefankroes/ancestry/issues/221 and https://github.com/stefankroes/ancestry/issues/241

I understand that there is https://github.com/stefankroes/ancestry/pull/262 which affects this PR as well. I'm fine with fixing support for this as soon as #262 is merged.

### CODE REVIEW

**Comment by kbrock** [comment]
Hi @walski Maybe #262 is trying to do too much. ideas how to pair that down?
Also, iof #262 is merged, would that meet your needs as well?

**Comment by walski** [comment]
@kbrock #262 would totally work for me. I need to support UUIDs in the ancestry column, that's all.

I do not completely understand what holds #262 back from being merged or what is the big problem there. Happy to help, though if I can.

**Comment by kbrock** [comment]
@walski That was my interpretation of half a dozen PR/issues.

I was hoping to get some feedback from @stefankroes before merging it. Or at least a thorough review pointing out if some of my assumption are ok. I'll comment over there.

**Comment by kbrock** [comment]
@walski just read over your comments again.

I hadn't realized that `:primary_key_format` was added to the docs, but looks like it was lost somewhere.

Updated #262 - seems our two are converging. Although, I'm specifying a single symbol vs including the delimiter (Which is the original usage)

**Comment by kbrock** [comment]
thanks for the help here.

I'm going to remove this feature.
let people setup their own validations if they find it necessary.

**Pull request closed without merging**
