### PR TITLE
Quote identifiers in scopes

### PR DESCRIPTION
**Pull request by lordjavac**
Used identifier quoting to prevent SQL issues and also cahnged case of SQL syntax to uppercase to match rails.

### CODE REVIEW

**Comment by kbrock** [comment]
this looks nice.
I can revive - any interest?

**Comment by lordjavac** [comment]
Sure, I'll take a look at updating it to the current master.

**Comment by lordjavac** [comment]
I've updated to the current master branch and reimplemented the change. Looks like the tests all pass. Let me know what you think.

**Comment by kbrock** [comment]
Merged. Had to rework to remove the merging.

In the future, you may want to look into feature branches and using something linke `git rebase upstream/master`

Thanks

**Comment by kbrock** [comment]
Merged. ==> [ref](https://github.com/stefankroes/ancestry/commit/7a5e0910f22eabe66bcd59d09dea2c59815dd00f)

I had to rebase to remove merging that you did. May want to consider using feature branches and something like `git rebase upstream/master`

Also looks like the email address you used on that commit is not associated with your github account. So it isn't properly linking it back to you.

Thanks again,
K

**Comment by lordjavac** [comment]
Thanks. I was trying to figure out how to reset the codebase to the current upstream master. I've also set my email address to be correct for the future. It had been using my work email.

**Comment by kbrock** [comment]
@lordjavac You can add your work email to your github account - then all the stuff will link to your github login.

Yea, it was a little tricky to wrangle these commits into good shape :)

**Pull request closed without merging**
